### ISSUE TITLE
Don't use jar files, use dependencies from mavenCentral/jCenter

### ISSUE THREAD

**Issue by krt16s** [pklinken/Earmouse#1]
Both remaining jar files, guava and joda-time, are available in mavenCentral, why not use those?

````
compile "com.google.guava:guava:17.0"
compile "joda-time:joda-time:2.5"
````

**Comment by krt16s** [comment]
I cannot see any changes regarding this, should I open a PR?

**Comment by pklinken** [comment]
Sure

**Comment by krt16s** [comment]
https://github.com/pklinken/Earmouse/pull/6

**Comment by pklinken** [comment]
Cheers :)
