### ISSUE TITLE
Custom exercises

### ISSUE THREAD

**Issue by eridal** [pklinken/Earmouse#11]
Hi,

First of all let me say a big thank you for such a good app. It is really helping me become a better musician!!

I'm currently using the app for studying and my teacher gave me group of intervals to practice and sometimes these assignments wont match with the options that the app provides. As an example my current assignment is _Seconds and Thirds, both Minor and Major, Descending_. 

How difficult it would be to create a window were we can manually pick the group of intervals that we want to train?

**Comment by pklinken** [comment]
Hi Martin,

Thanks for your feedback, I'm the glad to hear this app is helpful to you :)
At this time the app isn't under active development, but I'll take a look
this weekend to consider the options for implementing something like this.

**Comment by eridal** [comment]
Hi Paul,

Thanks for your answer.

I'm not familiar with the codebase but I'm willing to contribute to make earmouse better. Please let me know if there are some entry-level task I could take care to familiarize with the app.

This weekend I'll attempt to setup the project and build the app.

**Comment by pklinken** [comment]
What you could do is try to use the Python scripts used to create exercises:
[Create an individual module](https://github.com/pklinken/Earmouse/blob/master/Earmouse/tools/create_module.py) 
[Generate a list from the available modules in a directory](https://github.com/pklinken/Earmouse/blob/master/Earmouse/tools/create_list.py) 

When you have created a few of your own you can host them somewhere (I use Github Pages) and change the server settings in the app's preferences.
[This is where the standard modules are hosted for reference](http://pklinken.github.io/Earmouse/Earmouse_localized/list.json)

If you do end up making a bunch of exercises let me know; I might want to include them in the app :)

**Comment by eridal** [comment]
Hey, I was not able to build the app yet.

Seems like the newest Android Studio is built using Intellij and the emulator wont start. I will continue my research when time allows (aka weekends)
