### ISSUE TITLE
Custom modules host not taken into consideration when fetching a new module

### ISSUE THREAD

**Issue by kuba-orlik** [pklinken/Earmouse#12]
First of all, I love your app! I find it very useful :)

I wanted to create my own set of exercises and realized it's not possible, as even if I change the settings for the host url, the individual modules are still fetched from `pklinken.github.io`.

Steps to reproduce:

* host a server with own modules
* put it's domain and port into the settings
* load the list of exercises
* pick an exercise to install

Expected results: 

the app makes a request to the custom host, fetches the exercise details and displays them on screen

Actual result:

the app makes a request to the default `pklinken.github.io` server, fetching the pre-existing default exercises instead of the custom ones (if the id matches), or displays an empty screen (if there's no exercise of given id on the custom server).

The app *does* connect to the custom server when requesting the list of modules, but not when requesting information about a specific module.

I've confirmed this behavior by monitoring my phone's http traffic by `mitmproxy`:

```
GET http://192.168.1.104:8888/Earmouse/Earmouse_localized/list_en.json
        <- 200 application.json 157b 547ms
GET http://pklinken.github.io/Earmouse/Earmouse_localized/module_en_14.json
        <- 200 application/json 631b 645ms
```

That unfortunately makes me unable to install any custom modules :<

**Comment by kuba-orlik** [comment]
I did manage to overcome this with a redirecting proxy with custom rules, but it's far from convenient ;)

**Comment by pklinken** [comment]
Hi Kuba, thanks for reporting this!
I'll have a look at it and get back to you

**Comment by pklinken** [comment]
@kuba-orlik I've committed some changes that should resolve the issue. Would like to hear your feedback!
I'll look into getting the latest version on F-droid and Google Play over the weekend, but you can always build your own APK if you are in a hurry :)

**Comment by kuba-orlik** [comment]
That's awesome, thank you!

I've tried building it and came across the following error message from gradle: 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Earmouse-docs'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
         https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.jar
         https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
         https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.jar
     Required by:
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1 > com.android.tools.lint:lint-api:26.0.1 > com.android.tools.external.com-intellij:intellij-core:26.0.1
```

I don't have much experience with building Java apps, maybe I'm doing something wrong? I just threw `gradle .` at the newest code...

**Comment by pklinken** [comment]
I'm not sure about building the app from the command-line; I build the app in Android Studio.
An updated version is available on Google Play and F-Droid should follow whenever their automated build-system notices the update.
Feel free to re-open the issue if after testing you find this problem persists :)
