### ISSUE TITLE
Server with modules is not availabe

### ISSUE THREAD

**Issue by kolewu** [pklinken/Earmouse#3]
The server configured in the app to download new modules `deanderezwaartekracht.nl` is not available.  I will try to make the server configurable in the app.

For now if someone wants to use another server, the source code has to be changed.  If you want to provide your own server, you only need to create a directory `/Earmouse_localized/` on the given server, put in there the json-files from `Earmouse/assets/` and server them over *http*.

**Comment by pklinken** [comment]
Actually the modules in assets/ are the ones that are hard-coded in the app, the tools/ directory contains all the modules that were available thru the manager.
I don't have a place to host at the moment so I'll make a release that has them all hardcoded in, it does require a fresh re-install of the app to get them then.

**Comment by kolewu** [comment]
Why not host with github pages?

And making the adress configurable it would be possible for every user to provider her own modules without changing the application.

**Comment by pklinken** [comment]
I tried that shortly but it didn't work, if that should work as you say i will just use github.

**Comment by kolewu** [comment]
It's working like a charm.  I followed this page: [Creating Project Pages manually - User Documentation](https://help.github.com/articles/creating-project-pages-manually/) and only created a directory `Earmouse_localized`, copied the lists and modules from `Earmouse/tools` into this directory and pushed the new `gh_pages` branch: et voilà https://kolewu.github.io/Earmouse/Earmouse_localized/list_de.json

I would recommend checkout to its own directory, just to not mix up with your working copy of the code:
    git clone git@github.com:pklinken/Earmouse.git Earmouse-pages

and then the next steps.

**Comment by pklinken** [comment]
That worked.
https://github.com/pklinken/Earmouse/commit/c11cb4302d0e3483480e96e4f0e07965076d0b60
