### ISSUE TITLE
New module versions are not shown in the list

### ISSUE THREAD

**Issue by kolewu** [pklinken/Earmouse#4]
When I create a new version of a module and increase the `module_version`, it is not presented in the list of available modules and therefore cannot be installed / updated.

**Comment by pklinken** [comment]
I just added that field for later use but the Module class doesn't currently use it for anything.
```
/** Module version number
     * <p>
     * Not currently used for anything, planned use is for Module updates.
     */
    private int moduleVersion = 1;
```

**Comment by kolewu** [comment]
Then I will try to implement the logic, that uses the version number to show a renewed version of some module.
