### ISSUE TITLE
Hear the possible answers to learn before practising

### ISSUE THREAD

**Issue by kolewu** [pklinken/Earmouse#5]
It would be nice, to hear the musical phrases to learn them. Then the app can be used not only for practising.

I see two possibilities to implement this:

- make a special class for hearing and group the modules to this class. Then one can learn / hear at the class *header page* and practise with the corresponding modules
- in state `EXERCISE_READY_NOTPLAYED` make the answer buttons just play the phrase associated with it

**Comment by pklinken** [comment]
Nice suggestion, currently working on a solution where there is a 'practice mode' button that will allow a user to play each of the answers (and the 'question') before switching back to 'answer mode' to complete the exercise.
That way the user can try out different answers before making a choice and if that is incorrect, resume trying out other answers.

**Comment by pklinken** [comment]
[https://github.com/pklinken/Earmouse/commit/431e7747ec275d763fad44fcaed7232fbdfff5f2](url)
This seems to work, would welcome feedback.

**Comment by kolewu** [comment]
On my Moto G2 with Android 5.0.2 this version is working nicely and the Practice mode is a very nice addition.

But on my Lenovo Yoga Tab 3 10" it's no working.  It creates a fatal exception at this line in `Main.java`:
```java
        setContentView(R.layout.activity_main);
```
with this message in the log:
```
FATAL EXCEPTION: main
    Process: pk.contender.earmouse, PID: 20631
    java.lang.RuntimeException: Unable to start activity ComponentInfo{pk.contender.earmouse/pk.contender.earmouse.Main}:
        android.view.InflateException: Binary XML file line #50: Error inflating class fragment
```
The error is the same in upright and landscape mode.

It looks like some problem with `activity_main.xml (sw600dp)`. The first commit with the error is 1997384 but I can't find anything special in there.

**Comment by pklinken** [comment]
I'll check it out this weekend, never tested the app much on tablets

**Comment by kolewu** [comment]
The XML-file where the error occurs is `fragment_exercise.xml` at least the number changes when the fragment at line 50 will be moved a line down.

**Comment by pklinken** [comment]
https://github.com/pklinken/Earmouse/commit/9c2ffba6d6c4e358d9f3cdbbb53d697942d239c6
Now there is just another bug where rotating the device will not save the state of the practice toggle button.

**Comment by pklinken** [comment]
https://github.com/pklinken/Earmouse/commit/3610139baf4f7c70436514c62091f896f1a10b26

Let me know if you find any other bugs or suggestions about the functionality, before i close this issue.

**Comment by kolewu** [comment]
It works like a charm.  Only the play button doesn't play the last heard excercise but only the one prepared for the _answer mode_. Though it can be used to pause an practice excercise and then to continue it.

There is an error that I can only describe roughly.  Both are not accompanied by any message in catlog.

Sometimes the exercise breaks just at the beginning.  Just as if the button has been pressed twice and the second press just cancels the first.  But normally the second press just starts a new exercise.  I cannot reproduce this reliably, but sometimes it happens when I try to start the new exercise just at the moment when the current one ends.

Now when playing with this method (pressing a new exercise just when the current one ends, when the noise is away) I have managed to be in a state where the applications doesn't respond to any exercise input:
* the play button shows _pause_
* nothing can be heard
* button presses on the exercises doesn't have any effect

And in the logfile I see:
```
D/Debug: exerciseIndex: 1 positiveOffset:12 negativeOffset:0 delta: 17baseOffset: 24
D/Debug: exerciseIndex: 0 positiveOffset:12 negativeOffset:0 delta: 17baseOffset: 16
D/DEBUG: MediaFragment received play request but is not ready
D/Debug: exerciseIndex: 2 positiveOffset:12 negativeOffset:0 delta: 17baseOffset: 18
```
The message with _exerciseIndex_ everytime I press an exercise button and _received play_ when I press the play button (that shows _pause_).

I have not found any action to leave this state
* change to other module
* toggle mode

**Comment by pklinken** [comment]
>  Only the play button doesn't play the last heard excercise but only the one prepared for the answer mode. Though it can be used to pause an practice excercise and then to continue it.
That is intentional, but not ideal. Perhaps it is better to only associate the play button with the actual exercise and then lose the ability to pause the 'practice answers'. 
The other bug you are describing sounds like a race condition, I'll have a look at that.

**Comment by pklinken** [comment]
https://github.com/pklinken/Earmouse/commit/218315bd943dfd4020a9229b1f3d132f2fb68de2
Did some work on the MediaFragment, it is still possible that a button press is ignored, but the fragment should no longer end up in an unexpected state.
